<template>
  <UButton
    color="primary"
    variant="subtle"
    icon="i-lucide-github"
    to="https://github.com/mem0ai/personalized-deep-research"
    target="_blank"
  >
  </UButton>
</template>
